spring.application.name=qmeapp
server.port=8080
 
# Supabase PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ynoqehvytbnulrdvkcpa
spring.datasource.password=Mataidako1.
# spring.datasource.driver-class-name=org.postgresql.Driver
 
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
 
# JWT
app.jwt.secret=YOUR_SUPER_SECRET_JWT_KEY_MINIMUM_32_CHARS_LONG_HERE
app.jwt.expiration-ms=86400000
 
# CORS
app.cors.allowed-origins=*
 
# spring.application.name=qmeapp
# server.port=8080

# # Supabase PostgreSQL Connection
# spring.datasource.url=jdbc:postgresql://db.ynoqehvytbnulrdvkcpa.supabase.co:5432/postgres?sslmode=require
# spring.datasource.username=postgres
# spring.datasource.password=Mataidako1.
# # spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA / Hibernate
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # JWT
# app.jwt.secret=YOUR_SUPER_SECRET_JWT_KEY_MINIMUM_32_CHARS_LONG_HERE
# app.jwt.expiration-ms=86400000

# # CORS
# app.cors.allowed-origins=*

